//1째 Medida
Valor Total = SUM(Tabela[CampoValor])

//2째 Medida
Rank = RANKX(ALL(Tabela[CampoDimensao]),[Valor Total],,DESC)

//3째 Medida
Valor Acumulado = CALCULATE([Valor Total],TOPN([Rank],ALL(Tabela[CampoDimensao]),[Valor Total],DESC))

//4째 Medida
Valor % Acumulado = [Valor Acumulado] / CALCULATE([Valor Total],ALL(Tabela[CampoDimensao]))